name: Linter

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [ '13' ]
        os: [ 'ubuntu-latest' ]
        python: [ '2.7' ]
    name: ESLINT
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: |
          npm install -g yarn@legacy

      - name: Install OS dependencies for `headless-gl`
        run: |
          sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config

      - name: Install dependencies
        run: |
          make setup

      - name: JavaScript lint
        run: |
          make lint
